README.md, README.nob.md
Added a very simple how-to for Norwegian and English.
=> docs: Basic setup description

webpack.config.js
40 issues in codacy should now be resolved! 🎈 
None
Codacity tab "issues" empty on branch master
=> fix: Change config to use double quotes

README.md, README.nob.md
The structure was kind of strange with three "h1" headers. Changed it so only the title has h1.
None
Better structure in the files
=> fix: Update structure in markdown

package.json, webpack.config.js, yarn.lock
I was getting very tired of everything being compiled despite nothing having changed every single time I ran the application, and decided to set up caching.
Run yarn once
yarn run should take the normal amount of time the first time, then the second time it should be considerably faster, especially for slow computers.
=> chore: Set up caching for build

src/Layout/ComputationMenu/AlgorithmSelect.tsx, src/Layout/ComputationMenu/AutoComputeCheckbox.tsx, src/Layout/ComputationMenu/ComputationMenu.tsx, src/Layout/ComputationMenu/ResetButton.tsx, src/Layout/ComputationMenu/YearSelect.tsx, src/Layout/Presentation/presentation-utilities.ts, src/Layout/PresentationMenu/PresentationSettings/Disproportionality.tsx, src/Layout/PresentationMenu/PresentationSettings/DisproportionalitySelect.tsx, src/Layout/PresentationMenu/PresentationSettings/DistrictSelect.tsx, src/Layout/PresentationMenu/PresentationSettings/NoSeatsCheckbox.tsx, src/Layout/PresentationMenu/PresentationSettings/PresentationSettings.tsx, src/computation/computation-models.ts, src/computation/logic/algorithm-utilities.ts, src/computation/logic/distribute-levelling-seats.ts, src/computation/logic/lague-dhondt.ts
Adds a bit of documentation to helper methods and cleans up ComputationMenu so that relies more on components than on a huge wall of JSX markup.
See if the application behaves like it did before the change.
No deviations from standard setup.
It should behave like it used to.
=> Refactor and docs

package.json, src/Layout/ConnectedLayout.tsx, src/Layout/Presentation/ConnectedPresentation.tsx, src/Layout/Presentation/DistrictOverview/DistrictOverview.tsx, src/Layout/Presentation/ElectionOverview/ElectionOverview.tsx, src/Layout/Presentation/Presentation.tsx, src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx, src/Layout/PresentationMenu/PresentationSettings/ConnectedPresentationSettings.tsx, src/Layout/PresentationMenu/PresentationSettings/FiltersCheckbox.tsx, src/Layout/PresentationMenu/PresentationSettings/PresentationSettings.tsx, src/Layout/PresentationMenu/presentation-menu-actions.ts, src/Layout/PresentationMenu/presentation-menu-reducer.ts, src/Layout/PresentationMenu/presentation-menu-state.ts, src/computation/computation-models.ts, src/computation/logic/algorithm-utilities.ts, src/store/local-storage.ts, src/store/version.ts, src/utilities/district.ts, src/utilities/rt.tsx, yarn.lock
Whole host of changes here:
* Filters in ElectionOverview
* Application versioning
* Vulnerable seats displayed in SingleDistrict and DistrictOverview
* Refactored various things
Versioning works by modifying "version" in localStorage. That means that by some means you have to change the version to both compatible and incompatible values. 
The application should:
* not reset state when there is an existing compatible version
* reset state when there is an impossible, undefined, or incompatible version
Obtain data from Celius or other source that has correct data for at least the "standard parameter" elections so that the results can be compared.
The application should:
* display the vulnerable seat in every district in SingleDistrict, who was the runner up, and how many votes they would …
=> Lavinia v1.1.0

package.json, src/store/version.ts
Updates version fields to 2.5.0 (specifically the version.ts and the package.json ones).
closes #94
=> Update version to 2.5.0

src/Layout/Presentation/DistrictOverview/DistrictOverview.tsx, src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx, src/Layout/PresentationMenu/PresentationSelection/presentation-selection-utilities.ts
closes #97  
closes #103
closes #104
closes #105
=> Fix issues

src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx, src/utilities/district.ts
The only suitable function I found for changing the className for each table cell (to be marked) was the Cell function.
#98 
#96
=> Single district add indicators

README.md, README.nob.md
Adding code badges to display our code quality in the README.
=> docs: add code badges to README

src/Layout/ComputationMenu/ComputationMenu.tsx, src/Layout/Presentation/ElectionOverview/ElectionOverview.tsx, src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx, src/Layout/PresentationMenu/PresentationSettings/MergeDistrictsCheckbox.tsx, src/common/SmartNumericInput/SmartNumericInput.tsx, src/common/SmartNumericInputWithLabel/SmartNumericInputWithLabel.tsx, src/common/SmartNumericInputWithLabel/index.ts, src/common/index.ts
New file created: SmartNumericInputWithLabel.tsx
=> Fix bugs + a new feature 

src/Layout/PresentationMenu/presentation-menu-actions.ts, src/Layout/PresentationMenu/presentation-menu-state.ts
=> Set default showPartiesWithoutSeats true

src/Layout/ComputationMenu/ComputationMenu.tsx, src/common/SmartNumericInput/SmartNumericInput.tsx, src/common/SmartNumericInputWithLabel/SmartNumericInputWithLabel.tsx
=> Add is-hidden-touch optional-prop to SmartNumericInput

src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx, src/assets/index.html
Bypassed this:
`Lavinia-client/src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx:170:33 - Lambdas are forbidden in JSX attributes due to their rendering performance impa`ct
=> feat: Indicate winner row - SingleDistrict

src/Layout/ComputationMenu/ComputationMenu.tsx, src/Layout/ComputationMenu/ResetButton.tsx
The ResetButton (reset settings button) should not say "push me" when it got nothing to give.
=> highlight/not-hightlight ResetButton

README.md, README.nob.md
Updates the readme files with the changes since they were last updated.
Closes #134
=> feature: update readme

.gitignore, cypress/integration/computation_menu.spec.ts, cypress/integration/computation_modern_combinations_pt1.spec.ts, cypress/integration/computation_modern_combinations_pt2.spec.ts, cypress/integration/computation_old_combinations.spec.ts, cypress/support/index.d.ts, cypress/support/index.ts, package.json, src/utilities/api-requests.ts, yarn.lock
Disables clearing of local storage in Cypress.
Reduces Cypress data download 128MB -> 46MB
Reduces Cypress run time 140min -> 57 min
Closes #209 
Closes #210 
Closes #217
=> fix: disable clearing of local storage

cypress/integration/presentation_menu.spec.ts, src/utilities/district.ts
Hiding parties which did not receive any seats causes Single District to crash.
Closes #237
=> Fix: hiding parties crashes single district

src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx
Sorts the Single District table by total seats received.
Closes #234
=> Sort Single District by Total Seats

Jenkinsfile
Removes any tag containing the letter "v". This results in the correct tag being chosen.
Closes #270
=> fix: remove tags containing v

src/Layout/Presentation/Presentation.tsx, src/Layout/Presentation/presentation-utilities.ts
Changes Single Party view to filter parties by their national seats, rather than their local ones.
Closes #266
=> fix: Filter parties by national seats
