Project-Lavinia/Lavinia-client

package.json
src/app/Layout/ComputationSettings/SettingsReducer.ts
src/app/Layout/Logic/AlgorithmUtils.ts
src/app/Layout/SmartNumericInput/SmartNumericInput.tsx
src/app/Layout/index.ts
src/app/index.tsx
src/app/reducers/index.ts
src/app/store/index.ts
src/main.tsx
tslint.json
yarn.lock

There was some kind of annoying bug that caused TSLint settings to revert and not work as intended. Now everything works properly.
In addition there is now a precommit hook for TSLint that ensures any commit has a passing TSLint execution.
Annoyance: TSLint is run on all files, this can be made more efficient with another package.
Run yarn. Change something you know TSLint will be annoyed with, plus some formatting in a file, then commit it. 
There should be an error thrown when you commit, but all files should have been formatted in accordance with Prettier settings.
Remember to revert/undo your commit when done.

fix: Update TSLint settings to be correct

---

package.json
src/app/Layout/ComputationSettings/SettingMenuComponent.css
src/app/Layout/ComputationSettings/SettingMenuComponent.tsx
src/app/Layout/NavigationMenu/NavMenu.css
src/app/Layout/NavigationMenu/NavMenu.tsx
src/app/Layout/PresentationSettings/PresentationMenu.css
src/app/Layout/PresentationSettings/PresentationMenu.tsx
src/app/Layout/PresentationSettings/PresentationSelection.tsx
src/app/Layout/PresentationSettings/PresentationSettings.tsx
src/assets/index.html
src/main.css
src/main.tsx

CSS was broken after splitting the client out into its own repository. Some changes make it difficult to entirely replicate the old CSS (particularly that we use an updated version of Bootstrap, and that we now use style imports directly in components as opposed to using strings).
A few minor fixes here and there in addition, like updating the application description and the html title tags.
1. yarn start
A website with (very) similar appearance to the [old application](https://mandater-testing.azurewebsites.net), CSS behaving in an acceptably similar or equivalent way.

refactor: Fix css and meta information

---

package.json
src/app/store/index.ts
src/app/store/local-storage.ts
src/main.tsx
yarn.lock

Local storage state persistence was lost in the transition to a more loosely coupled setup. It has been re-added.
Run yarn so lodash gets set up correctly.
State should be loaded from local storage on application load. Every three seconds, the application saves state to local storage.

feat: Re-add state persistence

---

src/app/Layout/ComputationSettings/SettingMenuContainer.tsx
src/app/Layout/Presentation/PresentationComponent.tsx
src/app/Layout/Presentation/PresentationContainer.tsx
src/app/Layout/Presentation/Utilities/PresentationUtilities.ts
src/app/Layout/Presentation/Views/SingleCounty.tsx
src/app/Layout/Presentation/Views/SingleDistrict.tsx
src/app/Layout/Presentation/Views/index.ts
src/app/Layout/PresentationSettings/PresentationActions.ts
src/app/Layout/PresentationSettings/PresentationReducer.ts
src/app/Layout/PresentationSettings/PresentationSelection.tsx
src/app/Layout/PresentationSettings/PresentationSettings.tsx
src/app/Layout/PresentationSettings/PresentationSettingsContainer.tsx
src/app/Layout/PresentationSettings/PresentationState.ts
src/app/Layout/Types/ActionTypes.ts
src/app/Layout/Types/PresentationType.ts

A requested feature is to be able to view singular districts and how parties fared there. This is a first draft/attempt at that view. Be thorough in the review!
Make sure to use the browser console and clear the application data. State has been changed and I am unsure how that will impact your testing.
* There is a new button for accessing single district presentation
* When clicked, a table of a single district appears in the presentation section, and relevant settings appear in presentation settings
* Changing the new dropdown select results in changing the view with accurate results
* The button opens the default (Østfold, 2017 as of now)
* State is correctly stored and loaded as in all other views
* Page size is set to the number of parties that got mandates in the election (not just …

feat: Single district view

---

src/app/Layout/API/RequestedDataReducer.ts
src/app/Layout/Computation/ComputationReducer.ts
src/app/Layout/ComputationSettings/SettingMenuContainer.tsx
src/app/Layout/ComputationSettings/SettingsReducer.ts
src/app/Layout/Presentation/PresentationContainer.tsx
src/app/Layout/PresentationSettings/PresentationActions.ts
src/app/Layout/PresentationSettings/PresentationReducer.ts
src/app/Layout/PresentationSettings/PresentationSelection.tsx
src/app/Layout/PresentationSettings/PresentationSelectionButton.tsx
src/app/Layout/PresentationSettings/PresentationSelectionButtonContainer.tsx
src/app/Layout/PresentationSettings/PresentationSettings.tsx
src/app/Layout/PresentationSettings/PresentationSettingsContainer.tsx

"as" is bad and we should feel bad. I have altered most of our code to use strong typing instead. Exceptions are:
* **connect(...)** because changing them requires further research
* **createStore(...)** because this whole function is witchcraft
*  **request(...)** because this function uses "as" the way it was intended
There are also a few commits that clean up comments we really have no use for.
Nothing special.
The app should run as usual!
closes #18

refactor: Use strong typing where possible

---

src/app/Layout/ComputationSettings/SettingMenuContainer.tsx
src/app/Layout/LayoutComponent.tsx
src/app/Layout/LayoutContainer.tsx
src/app/Layout/PresentationSettings/PresentationSettingsContainer.tsx

For (semi-)strong typing, and fewer lines of code, we can use [TypeScript partials](https://www.typescriptlang.org/docs/handbook/advanced-types.html) instead of new interfaces.

refactor: Use partials where useful

---

package.json
src/app/Layout/Presentation/PresentationComponent.tsx
src/app/Layout/Presentation/Utilities/PresentationUtilities.ts
src/app/Layout/Presentation/Views/RemainderQuotients.tsx
src/app/Layout/PresentationSettings/PresentationSelection.tsx
src/app/Layout/PresentationSettings/PresentationSettings.tsx
src/app/Layout/Types/PresentationType.ts
yarn.lock

Adds a new view displaying district quotients and highlighted levelling seat wins. It also includes some utility functions for future use and some for imminent use. A dependency patch was added since there is no point in waiting to fix it.
Set it up and run it as usual, make sure to test various settings and look for errors/incongruences.
Make sure you remember to run yarn before starting it.
A new fancy view! Hooray!

Add view displaying district quotients and hilighted levelling seat wins

---

src/app/Layout/Presentation/PresentationComponent.tsx
src/app/Layout/Presentation/Utilities/ReduceUtilities.ts
src/app/Layout/Presentation/Views/DistrictOverview.tsx
src/app/Layout/Presentation/Views/ElectionOverview.tsx
src/app/Layout/Presentation/Views/SeatDistribution.tsx
src/app/Layout/Presentation/Views/SingleDistrict.tsx
src/app/Layout/PresentationSettings/PresentationSelection.tsx

Makes various improvements on existing tables
* Navigation is now conditional on table size
* There are sums/totals in footers
* Some new utilities to make .reduce more quickly understandable
* Width of district names and party names adapted more
* Party code columns are now spaced evenly and more narrowly to reduce the necessity of scrolling
* Percentage columns removed as they are generally just duplicate data taking up space in the UI; can be better represented in a chart either way if necessary
Make sure there aren't any major changes from the normal operation, and that the numbers are in fact correct.
Same as normal.
An improved series of tables!

Minor tweaks to tables

---

src/app/Layout/Presentation/PresentationComponent.tsx
src/app/Layout/Presentation/Views/ElectionOverview.tsx

When one calls a .reduce function on an empty array, it needs to have an initial number for the sum.
It's important to check that everything runs when data is reset/cleared as well as running on initialized data.

refactor: fix bug involving .reduce function

---

src/app/Layout/Presentation/PresentationComponent.tsx
src/app/Layout/Presentation/Utilities/PresentationUtilities.ts
src/app/Layout/Presentation/Views/LevellingSeatOverview.tsx
src/app/Layout/Presentation/Views/index.ts
src/app/Layout/PresentationSettings/PresentationSelection.tsx
src/app/Layout/Types/PresentationType.ts

Adds a new view displaying parties with levelling seats and the order of which they received them. Closes #29
Set it up and run it as usual, make sure to test various settings and look for errors/incongruences. Test it without deleting cache first and then delete cache and try again to ensure everything works as it's supposed to.
Make sure you remember to run yarn before starting it.
A new fancy view! Hooray!

feat: levelling seat overview

---

.github/pull_request_template.md

The original version requires some URL hocus pocus, this seems unnecessary as the general gist of all pull requests are the same here.

docs: move pull request template so it is default

---

src/Layout/Presentation/ConnectedPresentation.tsx
src/Layout/Presentation/ElectionOverview/ElectionOverview.tsx
src/Layout/Presentation/Presentation.tsx
src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx
src/Layout/Presentation/presentation-models.ts
src/Layout/PresentationMenu/PresentationSelection/PresentationSelection.tsx
src/Layout/PresentationMenu/PresentationSettings/ConnectedPresentationSettings.tsx
src/Layout/PresentationMenu/PresentationSettings/PresentationSettings.tsx
src/Layout/PresentationMenu/presentation-menu-actions.ts
src/Layout/PresentationMenu/presentation-menu-reducer.ts
src/Layout/PresentationMenu/presentation-menu-state.ts

This pull request adds the feature of disproportionality indexes, specifically the Gallagher and Loosemore-Hanby indexes. A select element on the views affected (ElectionOverview and SingleDistrict) allows the user to choose the index, which is displayed in the footer of the Proportionality column in the affected views.
The disproportionality results have to be compared with Celius to ensure calculations are at least reasonably sound (with the same degree of rounding). The user-interface has to be checked for potential bugs.
Due to adding new state it is recommended to reset the application data prior to testing. 
The proportionality results have to be compared to Celius. This might prove difficult given that Celius in many places "selects" 10 of the largest parties for display, whereas …

Feature: disproportionality indexes

---

src/Layout/ComputationMenu/ComputationMenu.tsx

Fixed the issue with the results being wrong when selecting 2009.
Compare the results of 2009 with Celius or Valgresultat.no
Correct results.

Fixed incorrect results on year change

---

src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx

Adds a column for Single District view that shows how many percent of the votes in the district each party received.
The percentages should be visible and correct.
Normal setup, no special configuration.
There should be a new column in Single District that shows the percentage votes of each party,
No related issue

Single district percent

---

src/Layout/ComputationMenu/ComputationMenu.tsx

District threshold appeared twice in the computation menu. This RP removes the duplicate.
Ensure that the district threshold still functions as normal.
No special setup required.
Parties should lose seats when the district threshold is increased.
closes #89

fix: removed duplicate of district threshold

---

src/Layout/ComputationMenu/ComputationMenu.tsx
src/Layout/ComputationMenu/ConnectedComputationMenu.tsx
src/Layout/Presentation/DistrictOverview/DistrictOverview.tsx
src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx
src/Layout/PresentationMenu/PresentationSettings/ConnectedPresentationSettings.tsx
src/Layout/PresentationMenu/PresentationSettings/MergeDistrictsCheckbox.tsx
src/Layout/PresentationMenu/PresentationSettings/PresentationSettings.tsx
src/Layout/PresentationMenu/presentation-menu-actions.ts
src/Layout/PresentationMenu/presentation-menu-reducer.ts
src/Layout/PresentationMenu/presentation-menu-state.ts
src/computation/logic/district-merging.ts
src/utilities/map.ts

Implements a checkbox that enables the user to naïvely simulate the difference between having 19 and 11 districts in an election. It combines the areas, populations, votes, etc. of the districts that were merged into the new districts.
Test that the presentation settings still behaves as they should. This is necessary because this PR adds another column in the presentation settings, so we need to ensure all are displayed correctly.
Test that the correct districts are merged and that the final sums are correct. We want to avoid merging wrong districts and otherwise summing the numbers incorrectly.
No special setup should be required.
The checkbox should only be visible for elections from 2005 and later.
When the checkbox is checked, there should only be 11 districts returned in the …

feat: implement merging of districts

---

src/computation/logic/district-merging.ts

Votes was not set after being updated, meaning that all changes were lost. This PR ensures that votes is being updated correctly.
closes #117

fix: ensure that votes is set

---

src/Layout/ComputationMenu/AlgorithmSelect.tsx
src/Layout/ComputationMenu/ComputationMenu.tsx
src/Layout/ComputationMenu/ConnectedComputationMenu.tsx
src/Layout/ComputationMenu/computation-menu-actions.ts
src/Layout/ComputationMenu/computation-menu-models.ts
src/Layout/ComputationMenu/computation-menu-state.ts
src/computation/computation-state.ts
src/computation/logic/algorithm-utilities.ts
src/requested-data/requested-data-models.ts
src/requested-data/requested-data-utilities.ts

Changes AlgorithmSelect to use AlgorithmType instead of number.
The algorithm type should load correctly and get reset correctly when restoring historical settings as well as when saving and loading changed settings.
closes #88

refactor: use AlgorithmType instead of number

---

.env.defaults
src/Layout/ComputationMenu/ConnectedComputationMenu.tsx
src/Layout/ComputationMenu/computation-menu-actions.ts
src/Layout/ConnectedLayout.tsx
src/computation/computation-state.ts
src/requested-data/requested-data-models.ts
src/requested-data/requested-data-utilities.ts

Migrate data requests and model processing from API 2.0.0 to 3.0.0. The original pipeline from API 1.0.0 remains unchanged as it will require more substantial code restructuring.
#138

refactor: migrate to API 3.0.0

---

src/computation/logic/distribute-levelling-seats.ts

Seats which were won by parties below the election threshold are now subtracted before the national distribution.
closes #136

fix: do not distribute seats won by parties below the election threshold

---

src/Layout/ComputationMenu/ComputationMenu.tsx
src/Layout/ComputationMenu/ConnectedComputationMenu.tsx
src/Layout/PresentationMenu/PresentationSettings/ConnectedPresentationSettings.tsx
src/Layout/PresentationMenu/PresentationSettings/PresentationSettings.tsx
src/Layout/PresentationMenu/PresentationSettings/Use2021DistributionCheckbox.tsx
src/Layout/PresentationMenu/presentation-menu-actions.ts
src/Layout/PresentationMenu/presentation-menu-reducer.ts
src/Layout/PresentationMenu/presentation-menu-state.ts
src/computation/computation-actions.ts

Enables users to use district metrics from 2021 instead of the original data from the original election. This is only available for elections after 2001, as we only calculate the distribution of district seats after that election.
**Important:** This PR relies on data introduced by [Lavinia-api#31](https://github.com/Project-Lavinia/Lavinia-api/pull/31), so that PR needs to be accepted before this one.
1. Start up a Lavinia-api instance of the branch from [Lavinia-api#31](https://github.com/Project-Lavinia/Lavinia-api/pull/31) locally on your computer
2. Configure Lavinia-client so it retrieves district metrics from the local API instance 
3. Proceed as usual
closes #80

feat: enable use of district data from 2021

---

src/Layout/Presentation/SingleDistrict/SingleDistrict.tsx
src/computation/logic/utils.ts
src/utilities/district.ts

Fixes the bug that occurs when attempting to distribute very few district seats on the districts.
Also fixes a bug, where the calculation of most vulnerable seat assumes that all districts have a district seat and hence crashes when some districts have 0 district seats.
closes #122 
closes #148

fix: handle few district seats

---

src/Layout/ComputationMenu/ComputationMenu.tsx
src/assets/index.html
src/common/SmartNumericInput/SmartNumericInput.tsx
src/common/SmartNumericInputWithLabel/SmartNumericInputWithLabel.tsx
src/common/TooltipInfo/TooltipInfo.tsx
src/common/TooltipInfo/index.ts
src/common/index.ts

Now you can write tooltip-text for each SmartNumericInput in ComputationMenu. Visible by hovering the info-icon next to the label.

add tooltip to SmartNumericInput

---

src/Layout/Presentation/LevellingSeatOverview/LevellingSeatOverview.tsx
src/utilities/rt.tsx

Correct the display of Levelingseat overview when there are 0 leveling seats.
Closes #176

fix: handle display of 0 leveling seats

---

src/Layout/ComputationMenu/ComputationMenu.tsx
src/Layout/PresentationMenu/PresentationSettings/NoSeatsCheckbox.tsx
src/Layout/PresentationMenu/PresentationSettings/PresentationSettings.tsx

Hides the show all parties check box when it does not make sense for the related view.
closes #170

feature: hide show all parties when it is not relevant

---

src/Layout/Presentation/ElectionOverview/ElectionOverview.tsx

Correctly handle the case when the current number of parties does not equal the number of parties from the previous result.
Closes #184

fix: handle compare when year changes

---

.env.defaults
cypress.json
src/Layout/ComputationMenu/ComputationMenu.tsx
src/Layout/ComputationMenu/ConnectedComputationMenu.tsx
src/Layout/ComputationMenu/computation-menu-actions.ts
src/Layout/ConnectedLayout.tsx
src/Layout/Presentation/presentation-utilities.ts
src/Layout/PresentationMenu/PresentationSettings/ConnectedPresentationSettings.tsx
src/Layout/PresentationMenu/PresentationSettings/PresentationSettings.tsx
src/computation/computation-actions.ts
src/computation/computation-models.ts
src/computation/computation-reducer.ts
src/computation/computation-state.ts
src/computation/logic/algorithm-utilities.ts
src/computation/logic/distribute-levelling-seats.ts
src/computation/logic/distribution.ts
src/computation/logic/district-merging.ts
src/computation/logic/execute-algorithm.ts
src/computation/logic/lague-dhondt.ts
src/computation/logic/quotient-dictionary.ts
src/computation/logic/utils.ts
src/requested-data/requested-data-actions.ts
src/requested-data/requested-data-models.ts
src/requested-data/requested-data-reducer.ts
src/requested-data/requested-data-state.ts
src/utilities/dictionary.ts
src/utilities/map.ts
src/utilities/number.ts

This PR separates the client entirely from API v1 so it only relies on API v3.
The migration should halve the amount of data downloaded from the API.
Closes #219

refactor: Migrate from API v1

---

src/Layout/Presentation/ElectionOverview/ElectionOverview.tsx

The table filter options hiding rows with 0 in the column should be indicated by ≠ 0 instead of > 0, as it will still show rows with values < 0.
Closes #239

fix: do not show 0 should be ≠ 0 not > 0

---

Jenkinsfile

Builds the client after running the tests, keeping the tests from clearing the dist directory.
Also reduces the number of files listed before each stage. (Avoids listing files from node modules)
Closes #269

fix: build after testing
